---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-cluster
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-cluster
spec:
  version: 8.13.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-cluster
spec:
  version: 8.13.1
  count: 1
  elasticsearchRef:
    name: quickstart