apiVersion: v1
kind: Service
metadata:
  name: kibana-expose
  namespace: elastic-cluster
spec:
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  type: LoadBalancer
  ports:
    - port: 5601
      targetPort: 5601